-- User-pulled weekly analysis report. One per ISO week per user, generated by
-- request-weekly-analysis edge function. Eligibility = measurements + 4 photos
-- in last 7 days, AND no existing report for this ISO week.

CREATE TABLE public.weekly_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  iso_year INTEGER NOT NULL,
  iso_week INTEGER NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  markdown TEXT NOT NULL,
  summary_for_journey_log TEXT,
  signals JSONB NOT NULL DEFAULT '{}'::jsonb,        -- snapshot of inputs (weight delta, checkin %, etc.)
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, iso_year, iso_week)
);

ALTER TABLE public.weekly_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own weekly reports"
  ON public.weekly_reports FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins manage weekly reports"
  ON public.weekly_reports FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE INDEX idx_weekly_reports_user_time
  ON public.weekly_reports (user_id, generated_at DESC);
